import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });
export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="es-logo.png" />
      </Head>
      <main className="bg-primary">
        <header className="grid h-screen place-items-center px-7">
          <Image
            src={"/es-logo-name.svg"}
            alt="Eternal Story logo"
            width={1000}
            height={1000}
            className="self-end"
          />
          <Image
            src={"/es-logo-font.svg"}
            alt="Eternal Story logo"
            width={200}
            height={200}
            className="self-start"
          />
        </header>
      </main>
    </>
  );
}
