import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import Landing from "@/components/Landing";
import Event from "@/components/Event";
import Product from "@/components/Product";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Eternal Story</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="es-logo.png" />
      </Head>
      <main className="bg-primary">
        <Landing />
        <Event />
        <Product />
      </main>
    </>
  );
}
